### ISSUE TITLE
"Evolução temporal" drop-down list selection isn't synced with the graphic when changing dams

### ISSUE THREAD

**Issue by lhsilva** [ricardoccpaiva/barragenspt#1]
Steps to reproduce:
- Select one dam;
- Select "10 anos" on the "Evolução temporal" drop-down list.
- Select another dam;

Expected:
- Graphic should keep the 10 years history.

What happens:
- "10 anos" is still selected in the drop-down list, but the graphic is updated back to default, showing 2 years of history only.

**Comment by ricardoccpaiva** [comment]
Thanks for reporting. I'll check and fix it.

**Comment by ricardoccpaiva** [comment]
Hi @lhsilva , the problem should now be fixed 👼 
https://github.com/ricardoccpaiva/barragenspt/commit/66b8e443ac830eeca7d626dc35e7bfa99b8fe62d

**Comment by lhsilva** [comment]
Yes, it is! :) GJ!
